name: Docker CI/CD with Tests

on:
  push:
    branches: [ "master" ]       # Push vào master thì build & chạy smoke
    tags: [ "v*.*.*" ]           # Build thêm khi có tag version
  pull_request:
    branches: [ "master" ]       # PR thì chỉ build & test (không push)
  schedule:
    - cron: "0 1 * * *"          # 1h sáng hàng ngày chạy regression
  workflow_dispatch:              # Cho phép chạy manual

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Build Docker image (no push yet)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true   # load image vào local Docker để run test
          tags: test-image:latest

      - name: Run Smoke Tests inside container
        run: |
          docker run --rm test-image:latest pytest -m smoke --disable-warnings -q --alluredir=reports/smoke

      - name: Upload Smoke Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: Reports/smoke

      - name: Push Docker image (only if tests pass)
        if: success() && github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  regression-tests:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Regression Tests inside container
      run: |
        docker build -t regression-image .
        docker run --rm regression-image pytest -m regression --disable-warnings --alluredir=reports/regression

    - name: Upload Regression Report
      uses: actions/upload-artifact@v4
      with:
        name: regression-report
        path: Reports/regression
